INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aberdeen ','APG','Phillips AAF ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aberdeen ','ABR','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Abilene ','DYS','Dyess AFB ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Abilene ','ABI','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Abingdon ','VJI','Virginia Highlands ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ada ','ADT','Ada ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Adak Island ','ADK','Adak Island Ns ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Adrian ','ADG','Lenawee County ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Afton ','AFO','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aiken ','AIK','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ainsworth ','ANW','Ainsworth ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akhiok ','AKK','Akhiok SPB ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akiachak ','KKI','Spb ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akiak ','AKI','Akiak ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akron CO ' ,'AKO','Colorado Plains Regional Airport ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akron/Canton OH ' ,'CAK','Akron/canton Regional ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akron/Canton ','AKC','Fulton International ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Akutan ','KQA','Akutan ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alakanuk ','AUK','Alakanuk ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alameda ','NGZ','NAS ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alamogordo ','HMN','Holloman AFB ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alamogordo ','ALM','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alamosa ','ALS','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Albany ','NAB','Albany NAS ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Albany ','ABY','Dougherty County ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Albany ','ALB','Albany International ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Albany ','CVO','Albany ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Albert Lea ','AEL','Albert Lea ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Albuquerque ','ABQ','Albuquerque International ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aleknagik ','WKK','Aleknagik ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aleneva ','AED','Aleneva ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alexander City AL ' ,'ALX','Thomas C Russell Fld ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alexandria LA ' ,'AEX','Alexandria International ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alexandria ','ESF','Esler Field ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alexandria ','AXN','Alexandria ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alexandria Bay ','AXB','Alexandria Bay ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Algona ','AXG','Algona ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alice ','ALI','International ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aliceville AL ' ,'AIV','George Downer ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alitak ','ALZ','Alitak SPB ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Allakaket ','AET','Allakaket ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alliance ','AIA','Alliance ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alma ','AMN','Gratiot Community ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alpena ','APN','Alpena County Regional ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alpine ','ALE','Alpine ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alton ','ALN','Alton ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Altus ','LTS','Altus AFB ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Altus ','AXS','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Alyeska ','AQY','Alyeska ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Amarillo  ' ,'AMA','Rick Husband Amarillo International ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Amarillo ','TDW','Tradewind ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ambler ','ABL','Ambler ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Amchitka ','AHT','Amchitka ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Amery ','AHH','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ames ','AMW','Ames ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Amityville ','AYZ','Zahns ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Amook ','AOS','Amook ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anacortes ','OTS','Anacortes ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anacostia ','NDV','USN Heliport ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anaheim ','ANA','Orange County Steel Salvage Heliport ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anaktuvuk ','AKP','Anaktuvuk ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anchorage ','EDF','Elmendorf Afb ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anchorage ','ANC','Ted Stevens Anchorage International Airport ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anchorage ','MRI','Merrill Field ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anderson ','AID','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anderson ','AND','Anderson ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Andrews ','ADR','Andrews ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Angel Fire ','AXX','Angel Fire ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Angola ','ANQ','Tri-State Steuben Cty ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Angoon ','AGN','Angoon ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anguilla ','RFK','Rollang Field ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aniak ','ANI','Aniak ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anita Bay ','AIB','Anita Bay ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ann Arbor MI ' ,'ARB','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Annapolis ','ANP','Lee ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Annette Island ','ANN','Annette Island ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anniston AL ' ,'ANB','Anniston Metropolitan ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anniston ','QAW','Ft Mcclellan Bus Trml ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anniston ','RLI','Reilly AHP ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anthony ','ANY','Anthony ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Antlers ','ATE','Antlers ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Anvik ','ANV','Anvik ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Apalachicola ','AAF','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Apple Valley ','APV','Apple Valley ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Appleton ','ATW','Outagamie County ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Arapahoe ','AHF','Municipal ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Arcata ','ACV','Arcata ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Arctic Village ','ARC','Arctic Village ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ardmore ','AHD','Downtown ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ardmore ','ADM','Ardmore Municipal Arpt ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Arlington Heights ','JLH','US Army Heliport ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Artesia ','ATS','Artesia ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Neptune ' ,'ARX','Asbury Park ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ashland ','ASX','Ashland ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Ashley ','ASY','Ashley ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Aspen ','ASE','Aspen ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Astoria ','AST','Astoria ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Athens ','AHN','Athens ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Athens ','ATO','Ohio University ','United States ','US ');
INSERT INTO airports100(city,airportCode,airportName,country,countryAbbrev) VALUES ('Athens ','MMI','McMinn County ','United States ','US ');
