CREATE DATABASE csu;

use csu;

CREATE TABLE csuCampuses(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
   campus VARCHAR(200) NOT NULL,
   location VARCHAR(200) NOT NULL,
   county VARCHAR(200) NOT NULL,
   year INTEGER NOT NULL
);

CREATE TABLE csuFees(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   campus INTEGER NOT NULL, 
   year INTEGER NOT NULL,
   campusFee INTEGER NOT NULL,
   FOREIGN KEY (campus) REFERENCES csuCampuses(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE csuDegrees(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
   campus INTEGER NOT NULL,
   year INTEGER NOT NULL, 
   degrees INTEGER NOT NULL,
   FOREIGN KEY (campus) REFERENCES csuCampuses(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE csuDisciplines(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   name VARCHAR(200)
);

CREATE TABLE csuDisciplineEnrollments(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT, 
   campus INTEGER NOT NULL,
   discipline INTEGER NOT NULL, 
   year INTEGER NOT NULL,
   undergraduate INTEGER NOT NULL,
   graduate INTEGER NOT NULL,
   FOREIGN KEY (campus) REFERENCES csuCampuses(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
   FOREIGN KEY (discipline) REFERENCES csuDisciplines(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE csuEnrollments(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   campus INTEGER NOT NULL,
   year INTEGER NOT NULL,
   totalEnrollment_ay INTEGER NOT NULL, 
   fte_ay INTEGER NOT NULL,
   FOREIGN KEY (campus) REFERENCES csuCampuses(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE csuFaculty(
   id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
   campus INTEGER NOT NULL,
   year INTEGER NOT NULL,
   facutly DECIMAL(5,1),  
   FOREIGN KEY (campus) REFERENCES csuCampuses(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);