INSERT INTO countries(countryName,continent) VALUES ('usa',1);
INSERT INTO countries(countryName,continent) VALUES ('germany',2);
INSERT INTO countries(countryName,continent) VALUES ('france',2);
INSERT INTO countries(countryName,continent) VALUES ('japan',3);
INSERT INTO countries(countryName,continent) VALUES ('italy',2);
INSERT INTO countries(countryName,continent) VALUES ('sweden',2);
INSERT INTO countries(countryName,continent) VALUES ('uk',2);
INSERT INTO countries(countryName,continent) VALUES ('korea',3);
INSERT INTO countries(countryName,continent) VALUES ('russia',2);
INSERT INTO countries(countryName,continent) VALUES ('nigeria',4);
INSERT INTO countries(countryName,continent) VALUES ('australia',5);
INSERT INTO countries(countryName,continent) VALUES ('new zealand',5);
INSERT INTO countries(countryName,continent) VALUES ('egypt',4);
INSERT INTO countries(countryName,continent) VALUES ('mexico',1);
INSERT INTO countries(countryName,continent) VALUES ('brazil',1);
