INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle malibu');
INSERT INTO carNames(model,make) VALUES ('buick','buick skylark 320');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth satellite');
INSERT INTO carNames(model,make) VALUES ('amc','amc rebel sst');
INSERT INTO carNames(model,make) VALUES ('ford','ford torino');
INSERT INTO carNames(model,make) VALUES ('ford','ford galaxie 500');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet impala');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth fury iii');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac catalina');
INSERT INTO carNames(model,make) VALUES ('amc','amc ambassador dpl');
INSERT INTO carNames(model,make) VALUES ('citroen','citroen ds-21 pallas');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO carNames(model,make) VALUES ('ford','ford torino (sw)');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth satellite (sw)');
INSERT INTO carNames(model,make) VALUES ('amc','amc rebel sst (sw)');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge challenger se');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth cuda 340');
INSERT INTO carNames(model,make) VALUES ('ford','ford mustang boss 302');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet monte carlo');
INSERT INTO carNames(model,make) VALUES ('buick','buick estate wagon (sw)');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona mark ii');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth duster');
INSERT INTO carNames(model,make) VALUES ('amc','amc hornet');
INSERT INTO carNames(model,make) VALUES ('ford','ford maverick');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun pl510');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen 1131 deluxe sedan');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 504');
INSERT INTO carNames(model,make) VALUES ('audi','audi 100 ls');
INSERT INTO carNames(model,make) VALUES ('saab','saab 99e');
INSERT INTO carNames(model,make) VALUES ('bmw','bmw 2002');
INSERT INTO carNames(model,make) VALUES ('amc','amc gremlin');
INSERT INTO carNames(model,make) VALUES ('ford','ford f250');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevy c20');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge d200');
INSERT INTO carNames(model,make) VALUES ('hi','hi 1200d');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun pl510');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet vega 2300');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen super beetle 117');
INSERT INTO carNames(model,make) VALUES ('amc','amc gremlin');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth satellite custom');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle malibu');
INSERT INTO carNames(model,make) VALUES ('ford','ford torino 500');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet impala');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac catalina brougham');
INSERT INTO carNames(model,make) VALUES ('ford','ford galaxie 500');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth fury iii');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge monaco (sw)');
INSERT INTO carNames(model,make) VALUES ('ford','ford country squire (sw)');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac safari (sw)');
INSERT INTO carNames(model,make) VALUES ('amc','amc hornet sportabout (sw)');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet vega (sw)');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac firebird');
INSERT INTO carNames(model,make) VALUES ('ford','ford mustang');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury capri 2000');
INSERT INTO carNames(model,make) VALUES ('opel','opel 1900');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 304');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat 124b');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla 1200');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 1200');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen model 111');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth cricket');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona hardtop');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt hardtop');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen type 3');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet vega');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto runabout');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet impala');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac catalina');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth fury iii');
INSERT INTO carNames(model,make) VALUES ('ford','ford galaxie 500');
INSERT INTO carNames(model,make) VALUES ('amc','amc ambassador sst');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury marquis');
INSERT INTO carNames(model,make) VALUES ('buick','buick lesabre custom');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile delta 88 royale');
INSERT INTO carNames(model,make) VALUES ('chrysler','chrysler newport royal');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda rx2 coupe');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador (sw)');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle concours (sw)');
INSERT INTO carNames(model,make) VALUES ('ford','ford gran torino (sw)');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth satellite custom (sw)');
INSERT INTO carNames(model,make) VALUES ('volvo','volvo 145e (sw)');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen 411 (sw)');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 504 (sw)');
INSERT INTO carNames(model,make) VALUES ('renault','renault 12 (sw)');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto (sw)');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 510 (sw)');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona mark ii (sw)');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt (sw)');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla 1600 (sw)');
INSERT INTO carNames(model,make) VALUES ('buick','buick century 350');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet malibu');
INSERT INTO carNames(model,make) VALUES ('ford','ford gran torino');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge coronet custom');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury marquis brougham');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet caprice classic');
INSERT INTO carNames(model,make) VALUES ('ford','ford ltd');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth fury gran sedan');
INSERT INTO carNames(model,make) VALUES ('chrysler','chrysler new yorker brougham');
INSERT INTO carNames(model,make) VALUES ('buick','buick electra 225 custom');
INSERT INTO carNames(model,make) VALUES ('amc','amc ambassador brougham');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth valiant');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet nova custom');
INSERT INTO carNames(model,make) VALUES ('amc','amc hornet');
INSERT INTO carNames(model,make) VALUES ('ford','ford maverick');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth duster');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen super beetle');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet impala');
INSERT INTO carNames(model,make) VALUES ('ford','ford country');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth custom suburb');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile vista cruiser');
INSERT INTO carNames(model,make) VALUES ('amc','amc gremlin');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota carina');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet vega');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 610');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda rx3');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury capri v6');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat 124 sport coupe');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet monte carlo s');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac grand prix');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat 128');
INSERT INTO carNames(model,make) VALUES ('opel','opel manta');
INSERT INTO carNames(model,make) VALUES ('audi','audi 100ls');
INSERT INTO carNames(model,make) VALUES ('volvo','volvo 144ea');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge dart custom');
INSERT INTO carNames(model,make) VALUES ('saab','saab 99le');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota mark ii');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile omega');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth duster');
INSERT INTO carNames(model,make) VALUES ('ford','ford maverick');
INSERT INTO carNames(model,make) VALUES ('amc','amc hornet');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet nova');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun b210');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla 1200');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet vega');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle malibu classic');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth satellite sebring');
INSERT INTO carNames(model,make) VALUES ('ford','ford gran torino');
INSERT INTO carNames(model,make) VALUES ('buick','buick century luxus (sw)');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge coronet custom (sw)');
INSERT INTO carNames(model,make) VALUES ('ford','ford gran torino (sw)');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador (sw)');
INSERT INTO carNames(model,make) VALUES ('audi','audi fox');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen dasher');
INSERT INTO carNames(model,make) VALUES ('opel','opel manta');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 710');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat 128');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat 124 tc');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic');
INSERT INTO carNames(model,make) VALUES ('subaru','subaru');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat x1.9');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth valiant custom');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet nova');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury monarch');
INSERT INTO carNames(model,make) VALUES ('ford','ford maverick');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac catalina');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet bel air');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth grand fury');
INSERT INTO carNames(model,make) VALUES ('ford','ford ltd');
INSERT INTO carNames(model,make) VALUES ('buick','buick century');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle malibu');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth fury');
INSERT INTO carNames(model,make) VALUES ('buick','buick skyhawk');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet monza 2+2');
INSERT INTO carNames(model,make) VALUES ('ford','ford mustang ii');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto');
INSERT INTO carNames(model,make) VALUES ('amc','amc gremlin');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac astro');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen dasher');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 710');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen rabbit');
INSERT INTO carNames(model,make) VALUES ('amc','amc pacer');
INSERT INTO carNames(model,make) VALUES ('audi','audi 100ls');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 504');
INSERT INTO carNames(model,make) VALUES ('volvo','volvo 244dl');
INSERT INTO carNames(model,make) VALUES ('saab','saab 99le');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic cvcc');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat 131');
INSERT INTO carNames(model,make) VALUES ('opel','opel 1900');
INSERT INTO carNames(model,make) VALUES ('capri','capri ii');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt');
INSERT INTO carNames(model,make) VALUES ('renault','renault 12tl');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevelle malibu classic');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge coronet brougham');
INSERT INTO carNames(model,make) VALUES ('amc','amc matador');
INSERT INTO carNames(model,make) VALUES ('ford','ford gran torino');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth valiant');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet nova');
INSERT INTO carNames(model,make) VALUES ('ford','ford maverick');
INSERT INTO carNames(model,make) VALUES ('amc','amc hornet');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevette');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet woody');
INSERT INTO carNames(model,make) VALUES ('volkswagen','vw rabbit');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge aspen se');
INSERT INTO carNames(model,make) VALUES ('ford','ford granada ghia');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac ventura sj');
INSERT INTO carNames(model,make) VALUES ('amc','amc pacer d/l');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen rabbit');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun b-210');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla');
INSERT INTO carNames(model,make) VALUES ('ford','ford pinto');
INSERT INTO carNames(model,make) VALUES ('volvo','volvo 245');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth volare premier v8');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 504');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota mark ii');
INSERT INTO carNames(model,make) VALUES ('mercedes-benz','mercedes-benz 280s');
INSERT INTO carNames(model,make) VALUES ('cadillac','cadillac seville');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevy c10');
INSERT INTO carNames(model,make) VALUES ('ford','ford f108');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge d100');
INSERT INTO carNames(model,make) VALUES ('honda','honda accord cvcc');
INSERT INTO carNames(model,make) VALUES ('buick','buick opel isuzu deluxe');
INSERT INTO carNames(model,make) VALUES ('renault','renault 5 gtl');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth arrow gs');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun f-10 hatchback');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet caprice classic');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile cutlass supreme');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge monaco brougham');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury cougar brougham');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet concours');
INSERT INTO carNames(model,make) VALUES ('buick','buick skylark');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth volare custom');
INSERT INTO carNames(model,make) VALUES ('ford','ford granada');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac grand prix lj');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet monte carlo landau');
INSERT INTO carNames(model,make) VALUES ('chrysler','chrysler cordoba');
INSERT INTO carNames(model,make) VALUES ('ford','ford thunderbird');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen rabbit custom');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac sunbird coupe');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla liftback');
INSERT INTO carNames(model,make) VALUES ('ford','ford mustang ii 2+2');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevette');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt m/m');
INSERT INTO carNames(model,make) VALUES ('subaru','subaru dl');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen dasher');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 810');
INSERT INTO carNames(model,make) VALUES ('bmw','bmw 320i');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda rx-4');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen rabbit custom diesel');
INSERT INTO carNames(model,make) VALUES ('ford','ford fiesta');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda glc deluxe');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun b210 gx');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic cvcc');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge diplomat');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury monarch ghia');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac phoenix lj');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet malibu');
INSERT INTO carNames(model,make) VALUES ('ford','ford fairmont (auto)');
INSERT INTO carNames(model,make) VALUES ('ford','ford fairmont (man)');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth volare');
INSERT INTO carNames(model,make) VALUES ('amc','amc concord');
INSERT INTO carNames(model,make) VALUES ('buick','buick century special');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury zephyr');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge aspen');
INSERT INTO carNames(model,make) VALUES ('amc','amc concord d/l');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet monte carlo landau');
INSERT INTO carNames(model,make) VALUES ('buick','buick regal sport coupe (turbo)');
INSERT INTO carNames(model,make) VALUES ('ford','ford futura');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge magnum xe');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevette');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 510');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge omni');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota celica gt liftback');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth sapporo');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile starfire sx');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 200-sx');
INSERT INTO carNames(model,make) VALUES ('audi','audi 5000');
INSERT INTO carNames(model,make) VALUES ('volvo','volvo 264gl');
INSERT INTO carNames(model,make) VALUES ('saab','saab 99gle');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 604sl');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen scirocco');
INSERT INTO carNames(model,make) VALUES ('honda','honda accord lx');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac lemans v6');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury zephyr 6');
INSERT INTO carNames(model,make) VALUES ('ford','ford fairmont 4');
INSERT INTO carNames(model,make) VALUES ('amc','amc concord dl 6');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge aspen 6');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet caprice classic');
INSERT INTO carNames(model,make) VALUES ('ford','ford ltd landau');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury grand marquis');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge st. regis');
INSERT INTO carNames(model,make) VALUES ('buick','buick estate wagon (sw)');
INSERT INTO carNames(model,make) VALUES ('ford','ford country squire (sw)');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet malibu classic (sw)');
INSERT INTO carNames(model,make) VALUES ('chrysler','chrysler lebaron town @ country (sw)');
INSERT INTO carNames(model,make) VALUES ('volkswagen','vw rabbit custom');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda glc deluxe');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt hatchback custom');
INSERT INTO carNames(model,make) VALUES ('amc','amc spirit dl');
INSERT INTO carNames(model,make) VALUES ('mercedes','mercedes benz 300d');
INSERT INTO carNames(model,make) VALUES ('cadillac','cadillac eldorado');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 504');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile cutlass salon brougham');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth horizon');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth horizon tc3');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 210');
INSERT INTO carNames(model,make) VALUES ('fiat','fiat strada custom');
INSERT INTO carNames(model,make) VALUES ('buick','buick skylark limited');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet citation');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile omega brougham');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac phoenix');
INSERT INTO carNames(model,make) VALUES ('volkswagen','vw rabbit');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla tercel');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet chevette');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 310');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet citation');
INSERT INTO carNames(model,make) VALUES ('ford','ford fairmont');
INSERT INTO carNames(model,make) VALUES ('amc','amc concord');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge aspen');
INSERT INTO carNames(model,make) VALUES ('audi','audi 4000');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corona liftback');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda 626');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 510 hatchback');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda glc');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge colt');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 210');
INSERT INTO carNames(model,make) VALUES ('volkswagen','vw rabbit c (diesel)');
INSERT INTO carNames(model,make) VALUES ('volkswagen','vw dasher (diesel)');
INSERT INTO carNames(model,make) VALUES ('audi','audi 5000s (diesel)');
INSERT INTO carNames(model,make) VALUES ('mercedes-benz','mercedes-benz 240d');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic 1500 gl');
INSERT INTO carNames(model,make) VALUES ('renault','renault lecar deluxe');
INSERT INTO carNames(model,make) VALUES ('subaru','subaru dl');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen rabbit');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 280-zx');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda rx-7 gs');
INSERT INTO carNames(model,make) VALUES ('triumph','triumph tr7 coupe');
INSERT INTO carNames(model,make) VALUES ('ford','ford mustang cobra');
INSERT INTO carNames(model,make) VALUES ('honda','honda accord');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth reliant');
INSERT INTO carNames(model,make) VALUES ('buick','buick skylark');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge aries wagon (sw)');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet citation');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth reliant');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota starlet');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth champ');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic 1300');
INSERT INTO carNames(model,make) VALUES ('subaru','subaru');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 210 mpg');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota tercel');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda glc 4');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth horizon 4');
INSERT INTO carNames(model,make) VALUES ('ford','ford escort 4w');
INSERT INTO carNames(model,make) VALUES ('ford','ford escort 2h');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen jetta');
INSERT INTO carNames(model,make) VALUES ('renault','renault 18i');
INSERT INTO carNames(model,make) VALUES ('honda','honda prelude');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 200sx');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda 626');
INSERT INTO carNames(model,make) VALUES ('peugeot','peugeot 505s turbo diesel');
INSERT INTO carNames(model,make) VALUES ('saab','saab 900s');
INSERT INTO carNames(model,make) VALUES ('volvo','volvo diesel');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota cressida');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 810 maxima');
INSERT INTO carNames(model,make) VALUES ('buick','buick century');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile cutlass ls');
INSERT INTO carNames(model,make) VALUES ('ford','ford granada gl');
INSERT INTO carNames(model,make) VALUES ('chrysler','chrysler lebaron salon');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet cavalier');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet cavalier wagon');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet cavalier 2-door');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac j2000 se hatchback');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge aries se');
INSERT INTO carNames(model,make) VALUES ('pontiac','pontiac phoenix');
INSERT INTO carNames(model,make) VALUES ('ford','ford fairmont futura');
INSERT INTO carNames(model,make) VALUES ('amc','amc concord dl');
INSERT INTO carNames(model,make) VALUES ('volkswagen','volkswagen rabbit l');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda glc custom l');
INSERT INTO carNames(model,make) VALUES ('mazda','mazda glc custom');
INSERT INTO carNames(model,make) VALUES ('plymouth','plymouth horizon miser');
INSERT INTO carNames(model,make) VALUES ('mercury','mercury lynx l');
INSERT INTO carNames(model,make) VALUES ('nissan','nissan stanza xe');
INSERT INTO carNames(model,make) VALUES ('honda','honda accord');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota corolla');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic');
INSERT INTO carNames(model,make) VALUES ('honda','honda civic (auto)');
INSERT INTO carNames(model,make) VALUES ('datsun','datsun 310 gx');
INSERT INTO carNames(model,make) VALUES ('buick','buick century limited');
INSERT INTO carNames(model,make) VALUES ('oldsmobile','oldsmobile cutlass ciera (diesel)');
INSERT INTO carNames(model,make) VALUES ('chrysler','chrysler lebaron medallion');
INSERT INTO carNames(model,make) VALUES ('ford','ford granada l');
INSERT INTO carNames(model,make) VALUES ('toyota','toyota celica gt');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge charger 2.2');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevrolet camaro');
INSERT INTO carNames(model,make) VALUES ('ford','ford mustang gl');
INSERT INTO carNames(model,make) VALUES ('volkswagen','vw pickup');
INSERT INTO carNames(model,make) VALUES ('dodge','dodge rampage');
INSERT INTO carNames(model,make) VALUES ('ford','ford ranger');
INSERT INTO carNames(model,make) VALUES ('chevrolet','chevy s-10');
