 INSERT INTO Songs(title) VALUES ('Overture');
INSERT INTO Songs(title) VALUES ('A Bar In Amsterdam');
INSERT INTO Songs(title) VALUES ('Demon Kitty Rag');
INSERT INTO Songs(title) VALUES ('Tea With Cinnamon');
INSERT INTO Songs(title) VALUES ('Hey Ho on the Devil''s Back');
INSERT INTO Songs(title) VALUES ('Wading in Deeper');
INSERT INTO Songs(title) VALUES ('Le Pop');
INSERT INTO Songs(title) VALUES ('Der Kapitan');
INSERT INTO Songs(title) VALUES ('Virginia Clemm');
INSERT INTO Songs(title) VALUES ('Play My Darling\,  Play');
INSERT INTO Songs(title) VALUES ('To the Sea');
INSERT INTO Songs(title) VALUES ('Mother Superior');
INSERT INTO Songs(title) VALUES ('Ain\'t no Thang');
INSERT INTO Songs(title) VALUES ('A Kiss Before You Go');
INSERT INTO Songs(title) VALUES ('I Will Dance (When I Walk Away)');
INSERT INTO Songs(title) VALUES ('Cherry Pie');
INSERT INTO Songs(title) VALUES ('Land of Confusion');
INSERT INTO Songs(title) VALUES ('Lady Marlene');
INSERT INTO Songs(title) VALUES ('Rock-Paper-Scissors');
INSERT INTO Songs(title) VALUES ('Cocktails and Ruby Slippers');
INSERT INTO Songs(title) VALUES ('Soviet Trumpeter');
INSERT INTO Songs(title) VALUES ('Loathsome M');
INSERT INTO Songs(title) VALUES ('Shepherds Song');
INSERT INTO Songs(title) VALUES ('Gypsy Flee');
INSERT INTO Songs(title) VALUES ('God\'s Great Dust Storm');
INSERT INTO Songs(title) VALUES ('Ouch');
INSERT INTO Songs(title) VALUES ('Listening to the World');
INSERT INTO Songs(title) VALUES ('Johnny Blowtorch');
INSERT INTO Songs(title) VALUES ('Flash');
INSERT INTO Songs(title) VALUES ('Driving After You');
INSERT INTO Songs(title) VALUES ('My Own Tune');
INSERT INTO Songs(title) VALUES ('Badlands');
INSERT INTO Songs(title) VALUES ('Old De Spain');
INSERT INTO Songs(title) VALUES ('Oh My God');
INSERT INTO Songs(title) VALUES ('Lady Gray');
INSERT INTO Songs(title) VALUES ('Shine Like Neon Rays');
INSERT INTO Songs(title) VALUES ('Flash in the Dark');
INSERT INTO Songs(title) VALUES ('My Dear');
INSERT INTO Songs(title) VALUES ('Bad Girl');
INSERT INTO Songs(title) VALUES ('Rockland');
INSERT INTO Songs(title) VALUES ('Curvaceous Needs');
INSERT INTO Songs(title) VALUES ('Borka');
INSERT INTO Songs(title) VALUES ('Let it Snow');
