INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Alexander Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Amador County','Amador','California','Sierra Foothills','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Amador-Mendocino-Sonoma Counties','N/A','California','N/A','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Anderson Valley','Mendocino','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Arroyo Grande Valley','San Luis Obispo','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Atlas Peak','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Bennett Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Calaveras County','Calaveras','California','Sierra Foothills','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('California','N/A','California','California','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Carneros','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Central Coast','N/A','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Chalk Hill','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Chalone','Monterey','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Contra Costa County','Contra Costa','California','Santa Cruz Mountains','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Dry Creek Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Edna Valley','San Luis Obispo','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Fiddletown','Amador','California','Sierra Foothills','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Green Valley of Russian River Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Guenoc Valley','Lake','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Happy Canyon of Santa Barbara','Santa Barbara','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Howell Mountain','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Knights Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Lake County','Lake','California','North Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Livermore Valley','Alameda','California','Santa Cruz Mountains','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Lodi','San Joaquin','California','Central Valley','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Mendocino County','Mendocino','California','North Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Monterey County','Monterey','California','Central Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Mount Harlan','San Benito','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Mount Vedeer','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Napa Valley','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Napa-Sonoma counties','N/A','California','North Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('North Coast','N/A','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Oakville','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Paso Robles','San Luis Obispo','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Red Hills Lake County','Lake','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Rockpile','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Russian River Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Rutherford','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('San Luis Obispo County','San Luis Obispo','California','Central Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Santa Barbara County','Santa Barbara','California','Central Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Santa Cruz Mountains','N/A','California','Santa Cruz Mountains','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Santa Lucia Highlands','Monterey','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Santa Maria Valley','Santa Barbara','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Santa Ynez Valley','Santa Barbara','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Shenandoah Valley','Amador','California','Sierra Foothills','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Sierra Foothills','N/A','California','Sierra Foothills','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Solano County','Solano','California','North Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Sonoma Coast','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Sonoma County','Sonoma','California','North Coast','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Sonoma Valley','Sonoma','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Sonoma-Lake Counties','N/A','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Spring Mountain District','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('St. Helena','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Sta. Rita Hills','Santa Barbara','California','Central Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Stags Leap District','Napa','California','North Coast','Yes');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Yolo County','Yolo','California','Central Valley','No');
INSERT INTO appellations(appelation,county,state,area,isAVA) VALUES ('Yountville','Napa','California','North Coast','Yes');
