INSERT INTO grapes(grape,color) VALUES ('Barbera','Red');
INSERT INTO grapes(grape,color) VALUES ('Cabernet Franc','Red');
INSERT INTO grapes(grape,color) VALUES ('Cabernet Sauvingnon','Red');
INSERT INTO grapes(grape,color) VALUES ('Chardonnay','White');
INSERT INTO grapes(grape,color) VALUES ('Grenache','Red');
INSERT INTO grapes(grape,color) VALUES ('Malbec','Red');
INSERT INTO grapes(grape,color) VALUES ('Marsanne','White');
INSERT INTO grapes(grape,color) VALUES ('Merlot','Red');
INSERT INTO grapes(grape,color) VALUES ('Mourvedre','Red');
INSERT INTO grapes(grape,color) VALUES ('Muscat','White');
INSERT INTO grapes(grape,color) VALUES ('Petite Sirah','Red');
INSERT INTO grapes(grape,color) VALUES ('Pinot Noir','Red');
INSERT INTO grapes(grape,color) VALUES ('Riesling','White');
INSERT INTO grapes(grape,color) VALUES ('Roussanne','White');
INSERT INTO grapes(grape,color) VALUES ('Sangiovese','Red');
INSERT INTO grapes(grape,color) VALUES ('Sauvignon Blanc','White');
INSERT INTO grapes(grape,color) VALUES ('Syrah','Red');
INSERT INTO grapes(grape,color) VALUES ('Tempranillo','Red');
INSERT INTO grapes(grape,color) VALUES ('Viognier','White');
INSERT INTO grapes(grape,color) VALUES ('Zinfandel','Red');
