INSERT INTO disciplines(Name) VALUES ('Agriculture');
INSERT INTO disciplines(Name) VALUES ('Architecture');
INSERT INTO disciplines(Name) VALUES ('Area Studies');
INSERT INTO disciplines(Name) VALUES ('Biological Sciences');
INSERT INTO disciplines(Name) VALUES ('Business and Management');
INSERT INTO disciplines(Name) VALUES ('Communications');
INSERT INTO disciplines(Name) VALUES ('Computer and Info. Sciences');
INSERT INTO disciplines(Name) VALUES ('Education');
INSERT INTO disciplines(Name) VALUES ('Engineering');
INSERT INTO disciplines(Name) VALUES ('Fine and Applied Arts');
INSERT INTO disciplines(Name) VALUES ('Foreign Languages');
INSERT INTO disciplines(Name) VALUES ('Health Professions');
INSERT INTO disciplines(Name) VALUES ('Home Economics');
INSERT INTO disciplines(Name) VALUES ('Interdisciplinary Studies');
INSERT INTO disciplines(Name) VALUES ('Letters');
INSERT INTO disciplines(Name) VALUES ('Library');
INSERT INTO disciplines(Name) VALUES ('Mathematics');
INSERT INTO disciplines(Name) VALUES ('Physical Sciences');
INSERT INTO disciplines(Name) VALUES ('Psychology');
INSERT INTO disciplines(Name) VALUES ('Public Affairs');
INSERT INTO disciplines(Name) VALUES ('Social Sciences');
INSERT INTO disciplines(Name) VALUES ('Undeclared');
