INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Bakersfield','Bakersfield','Kern',1965);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Channel Islands','Camarillo','Ventura',2002);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Chico','Chico','Butte',1887);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Dominguez Hills','Carson','Los Angeles',1960);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-East Bay','Hayward','Alameida',1957);
INSERT INTO Campuses(campus,location,county,year) VALUES ('Fresno State University','Fresno','Fresno',1911);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Fullerton','Fullerton','Orange',1957);
INSERT INTO Campuses(campus,location,county,year) VALUES ('Humboldt State University','Arcata','Humboldt',1913);
INSERT INTO Campuses(campus,location,county,year) VALUES ('Long Beach State University','Long Beach','Los Angeles',1949);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Los Angeles','Los Angeles','Los Angeles',1947);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California  Maritime Academy','Vallejo','Solano',1929);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Monterey Bay','Seaside','Monterey',1994);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Northridge','Northridge','Los Angeles',1958);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State Polytechnic University-Pomona','Pomona','Los Angeles',1938);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Sacramento','Sacramento','Sacramento',1947);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-San Bernardino','San Bernardino','San Bernardino',1960);
INSERT INTO Campuses(campus,location,county,year) VALUES ('San Diego State University','San Diego','San Diego',1897);
INSERT INTO Campuses(campus,location,county,year) VALUES ('San Francisco State University','San Francisco','San Francisco',1899);
INSERT INTO Campuses(campus,location,county,year) VALUES ('San Jose State University','San Jose','Santa Clara',1857);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California Polytechnic State University-San Luis Obispo','San Luis Obispo','San Luis Obispo',1901);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-San Marcos','San Marcos','San Diego',1989);
INSERT INTO Campuses(campus,location,county,year) VALUES ('Sonoma State University','Rohnert Park','Sonoma',1960);
INSERT INTO Campuses(campus,location,county,year) VALUES ('California State University-Stanislaus','Turlock','Stanislaus',1957);
